language: python
python: '2.7'
# command to install dependencies
install: pip install -r requirements.txt -r requirements_test.txt
# command to run tests
script: py.test test_server.py --cov save_parser
after_success: coveralls
